#!/bin/bash
# Needs BUILD_NUMBER, BRANCH_NAME, DOCKER_DATA_COMMAND, DOCKER_REPOSITORY and FROM_DOCKER_REPOSITORY
set -xe

FROM_DOCKER_IMAGE_TAG="${FROM_DOCKER_REPOSITORY}:${GIT_COMMIT}"
DOCKER_IMAGE_TAG="${DOCKER_REPOSITORY}:${GIT_COMMIT}"
DOCKER_CONTAINER_NAME="bedrock-${BRANCH_NAME}-${BUILD_NUMBER}"

docker run --name "$DOCKER_CONTAINER_NAME" "$FROM_DOCKER_IMAGE_TAG" "$DOCKER_DATA_COMMAND"
docker commit "$DOCKER_CONTAINER_NAME" "$DOCKER_IMAGE_TAG"
